language: php
php:
  - 5.3
  - 5.4

env:
  - NO_INTERACTION=1

before_script:
  - sh -c "hg clone https://code.google.com/p/chromium-compact-language-detector libcld"
  - sh -c "cd libcld && ./build.sh"
  - sh -c "phpize"
  - sh -c "./configure --with-libcld-dir=libcld"
  - sh -c "make"

script: make test

notifications:
  email:
    - lstrojny@php.net
