language: php
php:
  - 5.3
  - 5.4

env:
  - NO_INTERACTION=1

before_script:
  - sh -c "cd vendor/libcld && ./build.sh"
  - sh -c "phpize"
  - sh -c "./configure --with-libcld-dir=vendor/libcld"
  - sh -c "make clean"
  - sh -c "make"

script: make test

notifications:
  email:
    - lstrojny@php.net
